apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    spec:
      containers:
      serviceAccountName: {{ template "loadtester.fullname" . }}
      containers:
        - name: ns-labeler
          image: "bitnami/kubectl:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["kubectl label ns {{ .Release.Namespace }} istio-injection=enabled; kubectl label ns {{ .Release.Namespace }} ca.istio.io/override=true"]
      restartPolicy: OnFailure
